import aboveEveryNameImage from "../../assets/images/above-every-name-image.png";
import AbundantEntrancesImage from "../../assets/images/abundant-entrances-image.png";
import agbanilagbatanImage from "../../assets/images/agbanilagbatan-image.png";
import bearingGiftsImage from "../../assets/images/bearing-gifts-image.png";
import bringMeUnderImage from "../../assets/images/bring-me-under-image.png";
import chambersOfMajestyImage from "../../assets/images/chambers-of-majesty-image.png";
import cityOfStoneImage from "../../assets/images/city-of-stone-image.png";
import elohimTenderImage from "../../assets/images/elohim-tender-image.png";
import esteemYourWordImage from "../../assets/images/esteem-your-word-image.png";
import followYourWayImage from "../../assets/images/follow-your-way-image.png";
import giveUsUnderstandingImage from "../../assets/images/give-us-understanding-image.png";
import gloryToGloryImage from "../../assets/images/glory-to-glory-image.png";
import heavensReactImage from "../../assets/images/heavens-react-image.png";
import holySpiritSingImage from "../../assets/images/holy-spirit-sing-image.png";
import iChooseLifeImage from "../../assets/images/i-choose-life-image.png";
import jesusTheHighPriestImage from "../../assets/images/jesus-the-high-priest-image.png";
import lifeIsYourBusinessImage from "../../assets/images/life-is-your-business-image.png";
import lionKingImage from "../../assets/images/lion-king-image.png";
import measureOutToMeImage from "../../assets/images/measure-out-to-me-image.png";
import moLikeEmiMimoImage from "../../assets/images/mo-like-emi-mimo-image.png";
import noLightSoBrightImage from "../../assets/images/no-light-so-bright-image.png";
import publishSalvationImage from "../../assets/images/publish-salvation-image.png";
import radianceOfHisGloryImage from "../../assets/images/radiance-of-his-glory.png";
import ruachAdonaiImage from "../../assets/images/ruach-adonai-image.png";
import sendDownImage from "../../assets/images/send-down-image.png";

import defaultImage from "../../assets/images/default-cleft-image.png";

import { AboveEveryName } from "../songs/AboveEveryName";
import { AbundantEntrances } from "../songs/AbundantEntrances";
import { Agbanilagbatan } from "../songs/Agbanilagbatan";
import { AwayWithYou } from "../songs/AwayWithYou";
import { BalmOfGilead } from "../songs/BalmOfGilead";
import { BannerOfLove } from "../songs/BannerOfLove";
import { BeMyMan } from "../songs/BeMyMan";
import { BeXtra } from "../songs/BeXtra";
import { BearingGifts } from "../songs/BearingGifts";
import { BeholdTheLamb } from "../songs/BeholdTheLamb";
import { BidMeCome } from "../songs/BidMeCome";
import { BloodGoblet } from "../songs/BloodGoblet";
import { BringMeUnder } from "../songs/BringMeUnder";
import { ByTheTime } from "../songs/ByTheTime";
import { ByTheWordOfGod } from "../songs/ByTheWordOfGod";
import { CarryMe } from "../songs/CarryMe";
import { ChambersofMajesty } from "../songs/ChambersofMajesty";
import { ChristBeMagnified } from "../songs/ChristBeMagnified";
import { CityOfStone } from "../songs/CityOfStone";
import { ComeJesusCome } from "../songs/ComeJesusCome";
import { ComeManifest } from "../songs/ComeManifest";
import { ConsecrateMe } from "../songs/ConsecrateMe";
import { ConsumingFire } from "../songs/ConsumingFire";
import { CrucifiedWithChrist } from "../songs/CrucifiedWithChrist";
import { DavidsArising } from "../songs/DavidsArising";
import { DayOfVengeance } from "../songs/DayOfVengeance";
import { DigNewWells } from "../songs/DigNewWells";
import { DrawingMeCloser } from "../songs/DrawingMeCloser";
import { EarthlyItinerary } from "../songs/EarthlyItinerary";
import { Elohim } from "../songs/Elohim";
import { ElohimInheritance } from "../songs/ElohimInheritance";
import { ElohimsChampion } from "../songs/ElohimsChampion";
import { ElohimShalom } from "../songs/ElohimShalom";
import { ElohimTender } from "../songs/ElohimTender";
import { ElyonDonComeDown } from "../songs/ElyonDonComeDown";
import { EmiAjobina } from "../songs/EmiAjobina";
import { EsteemYourWord } from "../songs/EsteemYourWord";
import { EverlastingGod } from "../songs/EverlastingGod";
import { EverlastingToEverlasting } from "../songs/EverlastingToEverlasting";
import { ExcellentGlory } from "../songs/ExcellentGlory";
import { ExpireDarkness } from "../songs/ExpireDarkness";
import { EyesOnlyForYou } from "../songs/EyesOnlyForYou";
import { FatherAndTheSon } from "../songs/FatherAndTheSon";
import { FatherMe } from "../songs/FatherMe";
import { FillingMyCup } from "../songs/FillingMyCup";
import { ForMySoul } from "../songs/ForMySoul";

export const songLyrics = [
  {
    id: 118,
    title: "Above Every Name (Kabi Osi O)",
    description: <AboveEveryName />,
    lyrics: "View",
    listen: "listen",
    thumbnail: aboveEveryNameImage,
  },
  {
    id: 79,
    title: "Abundant Entrances",
    description: <AbundantEntrances />,
    lyrics: "View",
    listen: "listen",
    thumbnail: AbundantEntrancesImage,
  },
  {
    id: 98,
    title: "Agbanilagbatan",
    description: <Agbanilagbatan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: agbanilagbatanImage,
  },
  {
    id: 27,
    title: "Away With You",
    description: <AwayWithYou />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 39,
    title: "Balm Of Gilead",
    description: <BalmOfGilead />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 86,
    title: "Banner of Love",
    description: <BannerOfLove />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 168,
    title: "Be My Man",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 167,
    title: "Be Xtra",
    description: <BeXtra />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 161,
    title: "Bearing Gifts",
    description: <BearingGifts />,
    lyrics: "View",
    listen: "listen",
    thumbnail: bearingGiftsImage,
  },
  {
    id: 99,
    title: "Behold The Lamb",
    description: <BeholdTheLamb />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 112,
    title: "Bid Me Come",
    description: <BidMeCome />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 74,
    title: "Blood Goblet",
    description: <BloodGoblet />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 5,
    title: "Bring Me Under",
    description: <BringMeUnder />,
    lyrics: "View",
    listen: "listen",
    thumbnail: bringMeUnderImage,
  },
  {
    id: 22,
    title: "By The Time",
    description: <ByTheTime />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 35,
    title: "By The Word Of God",
    description: <ByTheWordOfGod />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 150,
    title: "Carry Me",
    description: <CarryMe />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 93,
    title: "Chambers of Majesty On High",
    description: <ChambersofMajesty />,
    lyrics: "View",
    listen: "listen",
    thumbnail: chambersOfMajestyImage,
  },
  {
    id: 149,
    title: "Christ Be Magnified",
    description: <ChristBeMagnified />,
    lyrics: "View",
    listen: "listen",
    thumbnail: chambersOfMajestyImage,
  },
  {
    id: 134,
    title: "City of Stone",
    description: <CityOfStone />,
    lyrics: "View",
    listen: "listen",
    thumbnail: cityOfStoneImage,
  },
  {
    id: 108,
    title: "Come Manifest Yourself To Me",
    description: <ComeManifest />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 119,
    title: "Come, Jesus Come",
    description: <ComeJesusCome />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 97,
    title: "Consecrate Me",
    description: <ConsecrateMe />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 38,
    title: "Consuming Fire",
    description: <ConsumingFire />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 104,
    title: "Crucified With Christ",
    description: <CrucifiedWithChrist />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 145,
    title: "Day Of Vengeance",
    description: <DayOfVengeance />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 71,
    title: "Davids Arising",
    description: <DavidsArising />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 124,
    title: "Dig New Wells",
    description: <DigNewWells />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 95,
    title: "Drawing Me Closer",
    description: <DrawingMeCloser />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 78,
    title: "Earthly Itinerary",
    description: <EarthlyItinerary />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 3,
    title: "Elyon Don Come Down",
    description: <ElyonDonComeDown />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 2,
    title: "Elohim",
    description: <Elohim />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 50,
    title: "Elohim Inheritance",
    description: <ElohimInheritance />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 146,
    title: "Elohim Shalom",
    description: <ElohimShalom />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 90,
    title: "Elohim Tender",
    description: <ElohimTender />,
    lyrics: "View",
    listen: "listen",
    thumbnail: elohimTenderImage,
  },
  {
    id: 80,
    title: "Elohim's Champion",
    description: <ElohimsChampion />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 151,
    title: "Emi Ajobiina",
    description: <EmiAjobina />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 30,
    title: "Everlasting God",
    description: <EverlastingGod />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 101,
    title: "Everlasting To Everlasting",
    description: <EverlastingToEverlasting />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 200,
    title: "Esteem Your Word",
    description: <EsteemYourWord />,
    lyrics: "View",
    listen: "listen",
    thumbnail: esteemYourWordImage,
  },
  {
    id: 116,
    title: "Excellent Glory",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 13,
    title: "Expire Darkness",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 166,
    title: "Eyes Only For You",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 126,
    title: "Father And The Son",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 127,
    title: "Father Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 107,
    title: "Filling My Cup",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 94,
    title: "For My Soul",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 10,
    title: "From The Well Of Salvation",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 114,
    title: "Gadol Adonai",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 59,
    title: "Gift To Man",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 69,
    title: "Give Us Understanding",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: giveUsUnderstandingImage,
  },
  {
    id: 25,
    title: "Glorious God",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 171,
    title: "Glory Call",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 28,
    title: "Glory Melody",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 116,
    title: "God Is Light",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 125,
    title: "God Looks Good On Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 178,
    title: "God Of All Grace",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 152,
    title: "Gonna Get God",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 135,
    title: "Great Adonai [Psalm 104]",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 138,
    title: "Great And Marvellous",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 105,
    title: "Hail The Lion Of Heaven",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: lionKingImage,
  },
  {
    id: 7,
    title: "Hail The Most High",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 67,
    title: "Hallelujah Chant",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 68,
    title: "Hallelujah To My King",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 16,
    title: "He Has Prevailed",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 91,
    title: "He Reigns",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 4,
    title: "He's God And A Man",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 18,
    title: "Heavens React",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: heavensReactImage,
  },
  {
    id: 117,
    title: "High Heavens",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 170,
    title: "Holy Jerusalem",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 76,
    title: "Holy Lamb Of God",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 137,
    title: "Holy Like You",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 75,
    title: "Holy Lowly",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 159,
    title: "How To Sing",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 41,
    title: "I Am A Mourner",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 96,
    title: "I Am That I Am",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: noLightSoBrightImage,
  },

  {
    id: 23,
    title: "I Become",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 129,
    title: "I Choose Life",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: iChooseLifeImage,
  },
  {
    id: 88,
    title: "I Follow You",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 158,
    title: "I Like The Holy Ghost (Mo Like Emi Mimo)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: moLikeEmiMimoImage,
  },
  {
    id: 11,
    title: "Iye Re (This Is Life)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 82,
    title: "Jaw Breaker",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 148,
    title: "Jesus Adonai (Life Is Your Business)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: lifeIsYourBusinessImage,
  },

  {
    id: 165,
    title: "Judge You Faithful",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 60,
    title: "Kadosh",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 48,
    title: "Last Last",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 154,
    title: "Lightly Esteem",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 89,
    title: "Lively Hope",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 24,
    title: "Look For A City",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 123,
    title: "Love Language",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },

  {
    id: 43,
    title: "Love Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 163,
    title: "Lover Of My Soul",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 83,
    title: "Majesty",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 92,
    title: "Many Mornings",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 29,
    title: "Marvel",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 44,
    title: "Master Lover",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 37,
    title: "Meek And Lowly Substances",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },

  {
    id: 63,
    title: "Mercy In Your Eye",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 26,
    title: "Mercy Look On Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 21,
    title: "More Beautiful",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 36,
    title: "Most Holy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 33,
    title: "My Devotion",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 58,
    title: "New Every Morning",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 34,
    title: "Oh The Blood",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 62,
    title: "Oh The Words Of Your Grace",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 49,
    title: "Olives Are Gathered",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 52,
    title: "Only You Can Satisfy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 40,
    title: "Opening Blind Eyes",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 131,
    title: "Order Of The Kingdom",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 51,
    title: "Our Forerunner",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 56,
    title: "Our God Reigneth",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 136,
    title: "Partake Of Life",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 45,
    title: "Perform Mercy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 31,
    title: "Pinnacle Of Joy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 115,
    title: "Praise Adonai",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 15,
    title: "Praise The Lord",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 140,
    title: "Prisoner Of Yahweh",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 156,
    title: "Radiance",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: radianceOfHisGloryImage,
  },
  {
    id: 53,
    title: "Ravish My Heart",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 65,
    title: "Reign In Life",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 17,
    title: "Resurrection And The Life",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 77,
    title: "Resurrect Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 109,
    title: "Ruach Adonai",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: ruachAdonaiImage,
  },
  {
    id: 42,
    title: "Safe In You",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 121,
    title: "Season Of The Spirit",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 120,
    title: "Seven Spirits Before The Throne",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 6,
    title: "Shine On Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 84,
    title: "Showers Of Mercy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 113,
    title: "Shulamite Woman",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 66,
    title: "So Holy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 174,
    title: "Songs Of Ascent",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 116,
    title: "Speak To Us (Publish Salvation)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: publishSalvationImage,
  },
  {
    id: 14,
    title: "Strong Crying And Tears",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 155,
    title: "Strong Tower (God Willing)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 54,
    title: "Subject Of His Will",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 55,
    title: "Sweet To My Taste",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 164,
    title: "Take Rest",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 182,
    title: "The Glory Ghost",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 175,
    title: "The Light Of The City",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 177,
    title: "The Pastors",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 73,
    title: "The Priest Is A Beast",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 147,
    title: "The Sacrifices Of God (Look On Me)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 102,
    title: "The Time Is At Hand!",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 1,
    title: "They Give Praise To God And To The Lamb",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 122,
    title: "This Generation",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 153,
    title: "Tidings Of Glory",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 12,
    title: "Tire L'Agbara",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 128,
    title: "To Him Who Sits Upon The Throne",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 85,
    title: "Touch My Hip",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 46,
    title: "Transfigure Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 169,
    title: "Utmost Fear",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 110,
    title: "Valiantly",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 130,
    title: "Walk With Patience",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 64,
    title: "Wail Jesus",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 9,
    title: "We Are Going To God ",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 173,
    title: "We Believe In Your Name",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 139,
    title: "We Bow Before Your Throne",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 20,
    title: "We Cry For Your Mercy",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 181,
    title: "We Receive Grace",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 141,
    title: "With You",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 176,
    title: "Worthy Archive",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 106,
    title: "Yahweh, Elohim",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: followYourWayImage,
  },
  {
    id: 144,
    title: "You Are God, No Doubt (Holy Spirit Sing)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: holySpiritSingImage,
  },
  {
    id: 143,
    title: "You Are Holy, El-Adonai",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 103,
    title: "You Are My Resting",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 32,
    title: "You Reign",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 132,
    title: "Your Commandments Of Everlasting Life",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: measureOutToMeImage,
  },
  {
    id: 72,
    title: "Your Law",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 133,
    title: "Your Love",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 47,
    title: "Your Promise",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 100,
    title: "Your Voice",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 180,
    title: "You Will Come",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 172,
    title: "Joy Unspeakable",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 179,
    title: "The Voice Of The Lord (Psalm 129)",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 19,
    title: "Thoroughly Excercised",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: jesusTheHighPriestImage,
  },
  {
    id: 57,
    title: "Make You Glad",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 70,
    title: "There Is A God",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 81,
    title: "Godly Fear",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 87,
    title: "The Lamb's Wife",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 111,
    title: "Smelling Everywhere",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 157,
    title: "Refine Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 900,
    title: "Glory To Glory",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: gloryToGloryImage,
  },
  {
    id: 911,
    title: "Send Down",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: sendDownImage,
  },
  {
    id: 183,
    title: "Mu Mi Wole Ogo",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 184,
    title: "Great And Terrible God",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 185,
    title: "Smelling Like A Ram",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 186,
    title: "I Find Grace",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 187,
    title: "Longing For Me",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 188,
    title: "All Of The Lights",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 189,
    title: "Ya Yesu Na",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 190,
    title: "Messiah The Priest",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 191,
    title: "I'll Be A Spirit",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 192,
    title: "A Heart Like Yours",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 193,
    title: "Ile Ni Jesu",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 194,
    title: "Mercy Conversations",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 195,
    title: "Jesus In His Garments",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 196,
    title: "Yah Yahweh",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 197,
    title: "High Power Plus",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 198,
    title: "Captivity",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 199,
    title: "Amen-Man",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 200,
    title: "Alufa",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 201,
    title: "More Excellent Name",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
  {
    id: 202,
    title: "Servant Like David",
    description: <BeMyMan />,
    lyrics: "View",
    listen: "listen",
    thumbnail: defaultImage,
  },
];
